### ISSUE TITLE
Traitement d'image avec Pillow

### ISSUE THREAD

**Issue by moz411** [pybdx/meetup-hub#1]
__Qui suis je: __ Anciennement consultant stockage/sauvegarde, je suis actuellement en formation Data Analyst. Je cherche à améliorer mes présentations à l'oral.
__Orateur__
__Type de format:__ court (30 min) ou workshop
__Toute entrée supplémentaire dans la TOC est la bienvenue__

# Comment un ordinateur voit une image.
## Compression

# Manipulations d'images en Python
## Élimination du bruit

# Filtrez une image

**Comment by garaud** [comment]
Salut, Merci pour la proposition et le détail.
Tu penses que tout ce contenu peut rentrer dans une présentation ? Est-ce que tu pourrais compléter avec quelques infos s'il te plait :+1:  "Qui vous êtes. Orateur. Besoin d'aide, Format + durée"

Merci et hâte de voir ça !
Damien

**Comment by garaud** [comment]
Toujours motivé et intéressé ?

Tu aurais des dates à soumettre en janvier par exemple ?

**Comment by moz411** [comment]
> Toujours motivé et intéressé ?
> 
> Tu aurais des dates à soumettre en janvier par exemple ?

Bonjour Damien ! Malheureusement je ne suis pas à Bordeaux cet hiver. 
J'ai travaillé récemment sur un datasource très intéressant : la base Quadrige de l'Ifremer, qui contient tout un tas d'information sur les niveaux de toxines et de chlorophylle-a des zones côtières, notamment le bassin d'Arcachon ! https://wwz.ifremer.fr/Recherche-Technologie/Departements-scientifiques/Focus/REPHY-REPHYTOX

Happy workshop,
Cdlt,

**Comment by garaud** [comment]
Merci pour les données, intéressant. Je note.

Et bien quand tu reviens par chez nous, tu n'hésite surtout pas !!

**Comment by garaud** [comment]
Je ferme. Si le sujet Pillow & traitement d'images revient sur le devant de la scène, n'hésitez pas à hurler au scandale.
