### ISSUE TITLE
Présentation MQTT

### ISSUE THREAD

**Issue by murlock** [pybdx/meetup-hub#2]
*Qui suis je*
Développeur issu du monde l'embarqué maintenant dans le stockage cloud

*Description courte*
Utilisation de MQTT, utilisé dans l'IOT (mais pas que) en Python avec découverte du protocole, point de sécuité et écoute des évènements de service publics

Orateur

Type de format: court (30 min) ou workshop

Juste un coup de relecture quand la presentation sera faite

**Comment by garaud** [comment]
Prévu pour le 2018-11-22 au mode *lightning talk*

cf. https://www.meetup.com/py-bdx/events/256121895/
