### ISSUE TITLE
Travail sur Odoo

### ISSUE THREAD

**Issue by Aquilog** [pybdx/meetup-hub#3]
Bonjour,
J'espère être au bon endroit pour poser ma question.
Travailleur indépendant, j'ai actuellement un surcroît de travail
Si un pythoniste est dispo envoyer mail à info@aquilog.fr
Merci d'avance

Guillaume JULLIEN

**Comment by garaud** [comment]
Bonjour Guillaume,
Je ne sais pas trop si c'est le bon endroit ou pas. En tout cas, on fera passer l'information lors d'un prochain meetup. L'idée, c'est de trouver un ou une développeuse Python pour faire du Odoo, c'est ça ?
Bon courage et à bientôt,
Damien

**Comment by garaud** [comment]
@Aquilog toujours d'actualité ?

Demain, le 22 nov 2018, y'a meetup Python au Node. Souhaites-tu venir et en dire un mot ?
https://www.meetup.com/py-bdx/events/256121895/

**Comment by garaud** [comment]
Je ferme cette issue. Si jamais quelqu'un·e veut présenter un truc sur Odoo, iel est la bienvenue.
